import { Dialog } from '@base-ui/react/dialog'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Link, useNavigate } from '@tanstack/react-router'
import { useState } from 'react'
import { AppShell } from '../components/AppShell'
import { Button } from '../components/Button'
import { SiteForm } from '../features/sites/SiteForm'
import { DeploymentLog } from '../features/deployments/DeploymentLog'
import { SiteConfiguration } from './SiteConfiguration'
import { api } from '../lib/api'
import { queryClient, queryKeys } from '../lib/query-client'

export function SitePage({ siteId }: { siteId: string }) {
  const site = useQuery({ queryKey: queryKeys.site(siteId), queryFn: () => api.site(siteId) })
  const auth = useQuery({ queryKey: queryKeys.auth, queryFn: api.authStatus })
  const health = useQuery({ queryKey: queryKeys.health, queryFn: api.health })
  const [duplicateWarning, setDuplicateWarning] = useState(false)
  const refresh = useMutation({ mutationFn: () => api.refreshRepository(siteId, auth.data?.csrf_token ?? '') })
  const deployments = useQuery({ queryKey: queryKeys.deployments(siteId), queryFn: () => api.deployments(siteId), refetchInterval: (query) => query.state.data?.some((item) => !['success', 'failed', 'cancelled'].includes(item.status)) ? 1500 : false })
  const analytics = useQuery({ queryKey: ['analytics', siteId], queryFn: () => api.analytics(siteId), refetchInterval: 30000 })
  const deploy = useMutation({ mutationFn: () => api.createDeployment(siteId, auth.data?.csrf_token ?? ''), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: queryKeys.deployments(siteId) }) } })
  if (site.isPending) return <AppShell><main className="mx-auto max-w-6xl px-6 py-14 text-sm text-muted">Loading site…</main></AppShell>
  if (site.isError) return <AppShell><main className="mx-auto max-w-6xl px-6 py-14 text-danger">{site.error.message}</main></AppShell>
  const running = deployments.data?.find((item) => !['success', 'failed', 'cancelled'].includes(item.status))
  const active = deployments.data?.find((item) => item.status === 'success')
  async function beginDeployment() {
    setDuplicateWarning(false)
    let latest
    try {
      latest = await refresh.mutateAsync()
    } catch {
      return
    }
    if (active?.commit_sha && latest.commit.sha === active.commit_sha) {
      setDuplicateWarning(true)
      return
    }
    deploy.mutate()
  }
  const stateLabel = running ? `Deploying · ${running.status.replaceAll('_', ' ')}` : active ? `Deployed · ${active.commit_sha?.slice(0, 12) ?? 'active release'}` : deployments.isPending ? 'Checking deployment…' : 'Not deployed'
  return <AppShell><main className="mx-auto max-w-6xl px-6 py-12"><Link to="/" className="text-sm text-muted hover:text-ink">← Sites</Link><div className="mt-10 flex flex-wrap items-end justify-between gap-5"><div><div className="flex items-center gap-3"><span className={`size-2 rounded-full ${running ? 'animate-pulse bg-primary' : active ? 'bg-primary' : 'bg-muted'}`} /><span className="text-sm text-muted">{stateLabel}</span></div><h1 className="mt-2 text-3xl font-semibold tracking-tight">{site.data.name}</h1><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-sm">{site.data.domains.length ? site.data.domains.map((domain) => <a key={domain} href={siteUrl(domain, health.data)} target="_blank" rel="noreferrer" className="text-muted underline decoration-border underline-offset-4 hover:text-primary hover:decoration-primary">{domain} ↗</a>) : <span className="text-muted">No domains configured</span>}</div></div><Link to="/sites/$siteId/settings" params={{ siteId }} className="inline-flex h-10 items-center border border-border bg-surface px-4 text-sm font-semibold hover:border-primary">Project settings</Link></div>
    <dl className="mt-10 grid border-y border-border sm:grid-cols-2"><Detail label="Repository" value={site.data.repository_url} /><Detail label="Branch" value={site.data.branch} /><Detail label="Project" value={site.data.project_directory} /><Detail label="Publish directory" value={site.data.publish_directory} /></dl>
    <section className="mt-8 border border-border bg-surface p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-medium">Repository cache</h2><p className="mt-1 text-sm text-muted">Fetch the configured branch and verify its latest commit.</p></div><Button tone="quiet" onClick={() => refresh.mutate()} disabled={refresh.isPending}>{refresh.isPending ? 'Fetching…' : 'Fetch repository'}</Button></div>{refresh.error && <p className="mt-4 text-sm text-danger">{refresh.error.message}</p>}{refresh.data && <div className="mt-5 border-t border-border pt-5"><p className="font-mono text-xs text-primary">{refresh.data.commit.sha.slice(0, 12)}</p><p className="mt-2 text-sm font-medium">{refresh.data.commit.message}</p><p className="mt-1 text-xs text-muted">{refresh.data.commit.author_name} · {new Date(refresh.data.commit.authored_at).toLocaleString()}</p></div>}</section>
    <section className="mt-10 border border-border bg-surface p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-medium">Deployments</h2><p className="mt-1 text-sm text-muted">Build an isolated checkout and atomically publish it when successful.</p></div><Button onClick={() => void beginDeployment()} disabled={deploy.isPending || refresh.isPending}>{deploy.isPending ? 'Queuing…' : refresh.isPending ? 'Checking branch…' : 'Deploy now'}</Button></div>{duplicateWarning && <div className="mt-5 border-l-2 border-primary bg-background px-4 py-4"><p className="text-sm font-medium">This commit is already the active release.</p><p className="mt-1 text-xs text-muted">Deploying it again will rebuild identical source. Continue only if you need a fresh build.</p><div className="mt-4 flex gap-2"><Button type="button" onClick={() => { setDuplicateWarning(false); deploy.mutate() }}>Deploy anyway</Button><Button type="button" tone="quiet" onClick={() => setDuplicateWarning(false)}>Cancel</Button></div></div>}{deploy.error && <p className="mt-4 text-sm text-danger">{deploy.error.message}</p>}<div className="mt-6 divide-y divide-border border-y border-border">{deployments.data?.map((item) => <Link key={item.id} to="/sites/$siteId/deployments/$deploymentId" params={{ siteId, deploymentId: item.id }} className="flex items-center justify-between gap-5 py-4 hover:text-primary"><div className="min-w-0"><p className="truncate text-sm font-medium">{item.triggered_by === 'rollback' ? `Rollback · ${item.commit_message ?? 'previous release'}` : item.commit_message ?? 'Waiting for checkout'}</p><p className="mt-1 font-mono text-xs text-muted">{item.commit_sha?.slice(0, 12) ?? item.id.slice(0, 12)} · {new Date(item.created_at).toLocaleString()}</p></div><Status value={item.status} /></Link>)}{deployments.data?.length === 0 && <p className="py-8 text-center text-sm text-muted">No deployments yet.</p>}</div></section>
    <section className="mt-10 border border-border bg-surface p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="font-medium">Traffic</h2><p className="mt-1 text-sm text-muted">Requests recorded by Chimney over the last 30 days.</p></div><span className="text-xs text-muted">{analytics.isPending ? 'Loading…' : analytics.isError ? 'Unavailable' : 'Live'}</span></div>{analytics.data && <><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Requests" value={analytics.data.total_requests.toLocaleString()} /><Metric label="Errors" value={analytics.data.error_requests.toLocaleString()} /><Metric label="Average response" value={`${analytics.data.average_duration_ms.toFixed(0)} ms`} /></div><div className="mt-6 divide-y divide-border border-y border-border">{analytics.data.daily.slice(0, 7).map((day) => <div key={day.day} className="flex items-center justify-between gap-4 py-3 text-sm"><span>{day.day}</span><span className="font-mono text-xs text-muted">{day.requests.toLocaleString()} requests · {day.errors.toLocaleString()} errors</span></div>)}{analytics.data.daily.length === 0 && <p className="py-6 text-sm text-muted">No requests recorded yet.</p>}</div></>}</section>
  </main></AppShell>
}

function siteUrl(domain: string, health?: Awaited<ReturnType<typeof api.health>>) { return `${health?.site_https_port ? 'https' : 'http'}://${domain}` }

function Detail({ label, value }: { label: string; value: string }) { return <div className="border-b border-border px-5 py-5 sm:nth-[odd]:border-r sm:nth-[-n+2]:border-t-0"><dt className="text-xs uppercase tracking-wider text-muted">{label}</dt><dd className="mt-2 break-all text-sm">{value}</dd></div> }

function Metric({ label, value }: { label: string; value: string }) { return <div className="border border-border bg-background p-4"><p className="text-xs uppercase tracking-wider text-muted">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div> }

function Status({ value }: { value: string }) { const done = value === 'success'; const failed = value === 'failed'; return <span className={`shrink-0 text-xs font-semibold uppercase tracking-wider ${done ? 'text-primary' : failed ? 'text-danger' : 'text-muted'}`}>{value.replaceAll('_', ' ')}</span> }

export function DeploymentPage({ siteId, deploymentId }: { siteId: string; deploymentId: string }) {
  const navigate = useNavigate()
  const auth = useQuery({ queryKey: queryKeys.auth, queryFn: api.authStatus })
  const deployment = useQuery({ queryKey: queryKeys.deployment(deploymentId), queryFn: () => api.deployment(deploymentId) })
  const history = useQuery({ queryKey: queryKeys.deployments(siteId), queryFn: () => api.deployments(siteId) })
  const rollback = useMutation({ mutationFn: () => api.rollbackDeployment(deploymentId, auth.data?.csrf_token ?? ''), onSuccess: async (created) => { queryClient.setQueryData(queryKeys.deployment(created.id), created); await queryClient.invalidateQueries({ queryKey: queryKeys.deployments(siteId) }); await navigate({ to: '/sites/$siteId/deployments/$deploymentId', params: { siteId, deploymentId: created.id } }) } })
  const retry = useMutation({ mutationFn: () => api.createDeployment(siteId, auth.data?.csrf_token ?? ''), onSuccess: async (created) => { queryClient.setQueryData(queryKeys.deployment(created.id), created); await queryClient.invalidateQueries({ queryKey: queryKeys.deployments(siteId) }); await navigate({ to: '/sites/$siteId/deployments/$deploymentId', params: { siteId, deploymentId: created.id } }) } })
  if (!deployment.data) return <AppShell><main className="mx-auto max-w-4xl px-6 py-14 text-sm text-muted">Loading deployment…</main></AppShell>
  const item = deployment.data
  const activeRelease = history.data?.find((candidate) => candidate.status === 'success')
  const isActive = Boolean(item.release_path && activeRelease?.release_path === item.release_path)
  return <AppShell><main className="mx-auto max-w-4xl px-6 py-12"><Link to="/sites/$siteId" params={{ siteId }} className="text-sm text-muted hover:text-ink">← Site</Link><div className="mt-10 flex flex-wrap items-center justify-between gap-5"><div><p className="font-mono text-xs text-muted">{item.commit_sha?.slice(0, 12) ?? item.id}</p><h1 className="mt-2 text-2xl font-semibold">{item.commit_message ?? 'Deployment'}</h1><p className="mt-2 text-xs uppercase tracking-wider text-muted">Triggered by {item.triggered_by}</p></div><div className="flex items-center gap-4"><Status value={item.status} />{isActive && <span className="border border-primary px-3 py-2 text-xs font-semibold uppercase tracking-wider text-primary">Active release</span>}{item.status === 'failed' && <Button onClick={() => retry.mutate()} disabled={retry.isPending}>{retry.isPending ? 'Queuing retry…' : 'Retry deployment'}</Button>}{item.status === 'success' && history.isSuccess && !isActive && <Button tone="quiet" onClick={() => rollback.mutate()} disabled={rollback.isPending}>{rollback.isPending ? 'Rolling back…' : 'Rollback to this release'}</Button>}</div></div>{(rollback.error || retry.error) && <p className="mt-6 border-l-2 border-danger pl-4 text-sm text-danger">{rollback.error?.message ?? retry.error?.message}</p>}{item.error_summary && <p className="mt-6 border-l-2 border-danger pl-4 text-sm text-danger">{item.error_summary}</p>}<DeploymentLog deploymentId={deploymentId} siteId={siteId} initialLog={item.log} initialStatus={item.status} /></main></AppShell>
}

export function SiteSettings({ siteId }: { siteId: string }) {
  const navigate = useNavigate()
  const site = useQuery({ queryKey: queryKeys.site(siteId), queryFn: () => api.site(siteId) })
  const auth = useQuery({ queryKey: queryKeys.auth, queryFn: api.authStatus })
  const deployKey = useQuery({ queryKey: queryKeys.deployKey(siteId), queryFn: () => api.deployKey(siteId) })
  const generateKey = useMutation({ mutationFn: () => api.generateDeployKey(siteId, auth.data?.csrf_token ?? ''), onSuccess: (data) => queryClient.setQueryData(queryKeys.deployKey(siteId), data) })
  const removeKey = useMutation({ mutationFn: () => api.deleteDeployKey(siteId, auth.data?.csrf_token ?? ''), onSuccess: () => queryClient.setQueryData(queryKeys.deployKey(siteId), { public_key: null }) })
  const renewCertificates = useMutation({ mutationFn: () => api.renewCertificates(siteId, auth.data?.csrf_token ?? '') })
  const remove = useMutation({ mutationFn: () => api.deleteSite(siteId, auth.data?.csrf_token ?? ''), onSuccess: async () => { queryClient.removeQueries({ queryKey: queryKeys.site(siteId) }); await queryClient.invalidateQueries({ queryKey: queryKeys.sites }); await navigate({ to: '/' }) } })
  const [tab, setTab] = useState<'project' | 'build' | 'domains' | 'routing' | 'access' | 'danger'>('project')
  const [keyCopied, setKeyCopied] = useState(false)
  const copyDeployKey = async () => {
    await navigator.clipboard.writeText(deployKey.data?.public_key ?? '')
    setKeyCopied(true)
    window.setTimeout(() => setKeyCopied(false), 2000)
  }
  if (!site.data) return <AppShell><main className="mx-auto max-w-4xl px-6 py-14 text-sm text-muted">Loading settings…</main></AppShell>
  const tabs = [['project', 'Project'], ['build', 'Build'], ['domains', 'Domains'], ['routing', 'Routing'], ['access', 'Repository access'], ['danger', 'Danger']] as const
  return <AppShell><main className="mx-auto max-w-4xl px-6 py-12"><Link to="/sites/$siteId" params={{ siteId }} className="text-sm text-muted hover:text-ink">← {site.data.name}</Link><div className="mt-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Project</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Project settings</h1><p className="mt-2 text-sm text-muted">Manage source, builds, domains, and repository access.</p></div>
    <div className="mt-8 flex overflow-x-auto border-b border-border" role="tablist">{tabs.map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={tab === value} onClick={() => setTab(value)} className={`shrink-0 border-b-2 px-4 py-3 text-sm font-semibold transition ${tab === value ? 'border-primary text-primary' : 'border-transparent text-muted hover:text-ink'}`}>{label}</button>)}</div>
    {tab === 'project' && <SiteForm site={site.data} section="project" />}
    {tab === 'build' && <SiteForm site={site.data} section="build" />}
    {tab === 'domains' && <><SiteForm site={site.data} section="domains" /><section className="mt-8 border border-border bg-surface p-6"><h2 className="font-medium">TLS certificates</h2><p className="mt-2 text-sm leading-6 text-muted">Ask Chimney to reload the configured domains and retry ACME certificate acquisition.</p><Button tone="quiet" type="button" className="mt-5" onClick={() => renewCertificates.mutate()} disabled={renewCertificates.isPending}>{renewCertificates.isPending ? 'Requesting…' : 'Reobtain certificates'}</Button>{renewCertificates.isSuccess && <p className="mt-3 text-xs text-primary">Certificate reload requested. ACME may take a moment to complete.</p>}{renewCertificates.error && <p className="mt-3 text-xs text-danger">{renewCertificates.error.message}</p>}</section></>}
    {tab === 'routing' && <SiteConfiguration siteId={siteId} embedded />}
    {tab === 'access' && <section className="mt-8 min-w-0 border border-border bg-surface p-6"><h2 className="font-medium">Private repository access</h2><p className="mt-2 text-sm leading-6 text-muted">Generate a read-only SSH key and add the public key to your Git provider.</p>{deployKey.data?.public_key ? <><pre className="mt-5 max-w-full whitespace-pre-wrap break-all border border-border bg-background p-4 text-xs leading-6 text-ink">{deployKey.data.public_key}</pre><div className="mt-4 flex flex-wrap gap-3"><Button tone="quiet" type="button" onClick={() => void copyDeployKey()} className={keyCopied ? 'border-primary text-primary' : ''}>{keyCopied ? '✓ Copied' : 'Copy public key'}</Button><Dialog.Root><Dialog.Trigger render={<Button tone="quiet" type="button" className="text-danger" />}>Remove key</Dialog.Trigger><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 bg-black/70" /><Dialog.Popup className="fixed left-1/2 top-1/2 w-[min(28rem,calc(100%-2rem))] -translate-x-1/2 -translate-y-1/2 border border-border bg-surface p-6"><Dialog.Title className="text-lg font-semibold">Remove this deploy key?</Dialog.Title><Dialog.Description className="mt-2 text-sm leading-6 text-muted">Private repository fetches and deployments will stop working until you generate and configure a replacement key.</Dialog.Description><div className="mt-6 flex justify-end gap-3"><Dialog.Close render={<Button tone="quiet" type="button" />}>Cancel</Dialog.Close><Dialog.Close render={<Button tone="quiet" type="button" className="text-danger" onClick={() => removeKey.mutate()} disabled={removeKey.isPending} />}>{removeKey.isPending ? 'Removing…' : 'Remove key'}</Dialog.Close></div></Dialog.Popup></Dialog.Portal></Dialog.Root></div><p className="sr-only" role="status" aria-live="polite">{keyCopied ? 'Public key copied to clipboard' : ''}</p></> : <Button tone="quiet" type="button" className="mt-5" onClick={() => generateKey.mutate()} disabled={generateKey.isPending || deployKey.isPending}>{generateKey.isPending ? 'Generating…' : 'Generate deploy key'}</Button>}{(generateKey.error || removeKey.error) && <p className="mt-4 text-sm text-danger">{generateKey.error?.message ?? removeKey.error?.message}</p>}</section>}
    {tab === 'danger' && <section className="mt-8 border border-danger/50 p-6"><h2 className="font-medium text-danger">Delete site</h2><p className="mt-2 text-sm text-muted">Permanently removes this site, its releases, and repository cache.</p><Dialog.Root><Dialog.Trigger render={<Button tone="quiet" className="mt-5 text-danger" />}>Delete site</Dialog.Trigger><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 bg-black/70" /><Dialog.Popup className="fixed left-1/2 top-1/2 w-[min(28rem,calc(100%-2rem))] -translate-x-1/2 -translate-y-1/2 border border-border bg-surface p-6"><Dialog.Title className="text-lg font-semibold">Delete {site.data.name}?</Dialog.Title><Dialog.Description className="mt-2 text-sm leading-6 text-muted">This cannot be undone.</Dialog.Description>{remove.error && <p className="mt-4 text-sm text-danger">{remove.error.message}</p>}<div className="mt-6 flex justify-end gap-3"><Dialog.Close render={<Button tone="quiet" />}>Cancel</Dialog.Close><Button onClick={() => remove.mutate()} disabled={remove.isPending} className="bg-danger text-black hover:bg-danger">{remove.isPending ? 'Deleting…' : 'Delete permanently'}</Button></div></Dialog.Popup></Dialog.Portal></Dialog.Root></section>}
  </main></AppShell>
}
