import { useQuery } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import { useState } from 'react'
import { AppShell } from '../components/AppShell'
import { api } from '../lib/api'

export function SiteAnalytics({ siteId }: { siteId: string }) {
  const [search, setSearch] = useState('')
  const analytics = useQuery({ queryKey: ['analytics', siteId, search], queryFn: () => api.analytics(siteId, search) })
  return <AppShell><main className="mx-auto max-w-6xl px-6 py-12"><Link to="/sites/$siteId" params={{ siteId }} className="text-sm text-muted hover:text-ink">← Site</Link><div className="mt-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Telemetry</p><h1 className="mt-2 text-3xl font-semibold">Request analytics</h1><p className="mt-2 text-sm text-muted">Detailed request telemetry from the last 30 days.</p></div>{analytics.data && <div className="mt-8 grid gap-3 sm:grid-cols-3"><Metric label="Requests" value={analytics.data.total_requests.toLocaleString()} /><Metric label="Errors" value={analytics.data.error_requests.toLocaleString()} /><Metric label="Average response" value={`${analytics.data.average_duration_ms.toFixed(0)} ms`} /></div>}<div className="mt-8 border border-border bg-surface p-5"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search path, host, method, device, or country" className="h-11 w-full border border-border bg-background px-3 text-sm outline-none focus:border-primary" /><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-b border-border text-muted"><tr>{['Time', 'Request', 'Status', 'Duration', 'Device', 'Country', 'IP'].map((heading) => <th key={heading} className="px-3 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{analytics.data?.requests.map((request) => <tr key={request.id}><td className="whitespace-nowrap px-3 py-3 text-muted">{new Date(`${request.created_at}Z`).toLocaleString()}</td><td className="max-w-[26rem] px-3 py-3"><span className="font-mono text-primary">{request.method}</span> <span className="break-all">{request.path}</span><span className="block text-muted">{request.host ?? 'unknown host'}</span></td><td className={request.status >= 400 ? 'px-3 py-3 text-danger' : 'px-3 py-3 text-primary'}>{request.status}</td><td className="px-3 py-3">{request.duration_ms} ms</td><td className="px-3 py-3">{request.device_type}</td><td className="px-3 py-3">{request.country ?? 'Unknown'}</td><td className="px-3 py-3 font-mono text-muted">{request.ip_address ?? 'Unknown'}</td></tr>)}</tbody></table>{analytics.data?.requests.length === 0 && <p className="py-10 text-center text-sm text-muted">No matching requests.</p>}</div></div></main></AppShell>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="border border-border bg-surface p-5"><p className="text-xs uppercase tracking-wider text-muted">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div> }
