import { useForm } from '@tanstack/react-form'
import { useMutation, useQuery } from '@tanstack/react-query'
import { useNavigate } from '@tanstack/react-router'
import { Button } from '../../components/Button'
import { api, type Site, type SiteInput } from '../../lib/api'
import { queryClient, queryKeys } from '../../lib/query-client'
import { DomainEditor } from './DomainEditor'
import { RepositoryDirectoryPicker } from './RepositoryDirectoryPicker'

const empty: SiteInput = { name: '', repository_url: '', branch: 'main', project_directory: '.', install_command: 'pnpm install --frozen-lockfile', build_command: 'pnpm build', publish_directory: 'dist', build_enabled: true, auto_deploy: false, domains: [] }
const initial = (site?: Site): SiteInput => site ? { name: site.name, repository_url: site.repository_url, branch: site.branch, project_directory: site.project_directory, install_command: site.install_command, build_command: site.build_command, publish_directory: site.publish_directory, build_enabled: site.build_enabled, auto_deploy: site.auto_deploy, domains: site.domains } : empty
const fieldClass = 'mt-2 h-11 w-full border border-border bg-surface px-3 outline-none transition focus:border-primary'
const required = (label: string, max: number) => ({ value }: { value: string }) => !value.trim() ? `${label} is required.` : value.length > max ? `${label} must be ${max} characters or fewer.` : /[\u0000-\u001f\u007f]/.test(value) ? `${label} contains unsupported control characters.` : undefined
const pathRule = (label: string) => ({ value }: { value: string }) => !value || value.length > 512 || value.startsWith('/') || value.includes('\\') || value.split('/').includes('..') ? `${label} must be a relative path inside the repository.` : undefined
const branchRule = ({ value }: { value: string }) => !value || value.length > 255 || value.startsWith('-') || value.startsWith('/') || value.endsWith('/') || value.endsWith('.') || value.endsWith('.lock') || value.includes('//') || value.includes('..') || value.includes('@{') || /[~^:?*[\\\s]/.test(value) ? 'Enter a valid Git branch name.' : undefined

function Errors({ errors }: { errors: unknown[] }) { return errors.length ? <span className="mt-2 block text-xs text-danger">{errors.map(String).join(' ')}</span> : null }

export function SiteForm({ site }: { site?: Site }) {
  const navigate = useNavigate()
  const auth = useQuery({ queryKey: queryKeys.auth, queryFn: api.authStatus })
  const mutation = useMutation({
    mutationFn: (input: SiteInput) => site ? api.updateSite(site.id, input, auth.data?.csrf_token ?? '') : api.createSite(input, auth.data?.csrf_token ?? ''),
    onSuccess: async (saved) => { queryClient.setQueryData(queryKeys.site(saved.id), saved); await queryClient.invalidateQueries({ queryKey: queryKeys.sites }); await navigate({ to: '/sites/$siteId', params: { siteId: saved.id } }) },
  })
  const form = useForm({ defaultValues: initial(site), onSubmit: ({ value }) => mutation.mutateAsync(value) })
  const inspection = useMutation({ mutationFn: () => api.inspectRepository(form.getFieldValue('repository_url'), auth.data?.csrf_token ?? ''), onSuccess: (result) => { if (result.default_branch && form.getFieldValue('branch') === 'main') form.setFieldValue('branch', result.default_branch) } })
  const detection = useMutation({ mutationFn: () => api.detectBuild(site?.id ?? '', auth.data?.csrf_token ?? ''), onSuccess: (result) => { form.setFieldValue('install_command', result.install_command); form.setFieldValue('build_command', result.build_command); form.setFieldValue('publish_directory', result.publish_directory); form.setFieldValue('build_enabled', Boolean(result.build_command)) } })

  return <form onSubmit={(event) => { event.preventDefault(); event.stopPropagation(); void form.handleSubmit() }} className="mt-8 space-y-8" noValidate>
    <section className="grid gap-5 border border-border bg-surface p-6 sm:grid-cols-2"><div className="sm:col-span-2"><h2 className="font-medium">Repository</h2><p className="mt-1 text-sm text-muted">The source and project location within it.</p></div>
      <form.Field name="name" validators={{ onBlur: required('Site name', 100) }}>{(field) => <label className="text-sm font-medium">Site name<input value={field.state.value} onBlur={field.handleBlur} onChange={(event) => field.handleChange(event.target.value)} className={fieldClass} /><Errors errors={field.state.meta.errors} /></label>}</form.Field>
      <form.Field name="repository_url" validators={{ onBlur: required('Repository URL', 2048) }}>{(field) => <label className="text-sm font-medium">Repository URL<input value={field.state.value} onBlur={field.handleBlur} onChange={(event) => { field.handleChange(event.target.value); inspection.reset() }} placeholder="https://github.com/owner/site.git" className={fieldClass} /><button type="button" disabled={!field.state.value || inspection.isPending} onClick={() => inspection.mutate()} className="mt-2 text-xs font-semibold text-primary disabled:text-muted">{inspection.isPending ? 'Inspecting…' : 'Inspect repository'}</button><Errors errors={field.state.meta.errors} />{inspection.isError && <span className="mt-2 block text-xs text-danger">{inspection.error.message}</span>}{inspection.data && <span className="mt-2 block text-xs text-muted">Found {inspection.data.branches.length} branches{inspection.data.default_branch ? ` · default: ${inspection.data.default_branch}` : ''}</span>}</label>}</form.Field>
      <form.Field name="branch" validators={{ onBlur: branchRule }}>{(field) => <label className="text-sm font-medium">Branch{inspection.data?.branches.length ? <select value={field.state.value} onBlur={field.handleBlur} onChange={(event) => field.handleChange(event.target.value)} className={fieldClass}>{!inspection.data.branches.includes(field.state.value) && <option value={field.state.value}>{field.state.value}</option>}{inspection.data.branches.map((branch) => <option key={branch}>{branch}</option>)}</select> : <input value={field.state.value} onBlur={field.handleBlur} onChange={(event) => field.handleChange(event.target.value)} className={fieldClass} />}<Errors errors={field.state.meta.errors} /></label>}</form.Field>
      <form.Field name="project_directory" validators={{ onBlur: pathRule('Project directory') }}>{(field) => <label className="text-sm font-medium">Project directory<input value={field.state.value} onBlur={field.handleBlur} onChange={(event) => field.handleChange(event.target.value)} className={fieldClass} />{site ? <RepositoryDirectoryPicker siteId={site.id} branch={form.getFieldValue('branch')} value={field.state.value} onSelect={field.handleChange} /> : <span className="mt-2 block text-xs text-muted">Create the site first to browse its repository.</span>}<Errors errors={field.state.meta.errors} /></label>}</form.Field>
    </section>
    <section className="grid gap-5 border border-border bg-surface p-6 sm:grid-cols-2"><div className="sm:col-span-2"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-medium">Build and publish</h2><form.Field name="build_enabled">{(field) => <label className="mt-4 flex items-center gap-3 text-sm text-muted"><input type="checkbox" checked={field.state.value} onChange={(event) => field.handleChange(event.target.checked)} className="size-4 accent-primary" />Run a build before publishing</label>}</form.Field></div>{site && <Button type="button" tone="quiet" onClick={() => detection.mutate()} disabled={detection.isPending}>{detection.isPending ? 'Detecting…' : 'Detect settings'}</Button>}</div>{detection.data && <p className="mt-4 text-xs text-muted">Detected {detection.data.detected_framework ?? 'a web project'} · {detection.data.repository_mise ? 'using repository Mise config' : `tools: ${detection.data.tools.join(', ') || 'none'}`}.</p>}{detection.error && <p className="mt-4 text-xs text-danger">{detection.error.message}</p>}</div>
      <form.Subscribe selector={(state) => state.values.build_enabled}>{(enabled) => enabled ? <><form.Field name="install_command">{(field) => <label className="text-sm font-medium">Install command<input value={field.state.value ?? ''} onChange={(event) => field.handleChange(event.target.value || null)} className={fieldClass} /></label>}</form.Field><form.Field name="build_command">{(field) => <label className="text-sm font-medium">Build command<input value={field.state.value ?? ''} onChange={(event) => field.handleChange(event.target.value || null)} className={fieldClass} /></label>}</form.Field></> : null}</form.Subscribe>
      <form.Field name="publish_directory" validators={{ onBlur: pathRule('Publish directory') }}>{(field) => <label className="text-sm font-medium">Publish directory<input value={field.state.value} onBlur={field.handleBlur} onChange={(event) => field.handleChange(event.target.value)} className={fieldClass} /><Errors errors={field.state.meta.errors} /></label>}</form.Field>
      <form.Field name="domains" mode="array">{(field) => <DomainEditor value={field.state.value} onChange={field.handleChange} />}</form.Field>
    </section>
    {mutation.error && <p role="alert" className="border-l-2 border-danger pl-3 text-sm text-danger">{mutation.error.message}</p>}
    <form.Subscribe selector={(state) => [state.canSubmit, state.isSubmitting] as const}>{([canSubmit, isSubmitting]) => <div className="flex justify-end"><Button type="submit" disabled={!canSubmit || isSubmitting || mutation.isPending}>{isSubmitting || mutation.isPending ? 'Saving…' : site ? 'Save changes' : 'Create site'}</Button></div>}</form.Subscribe>
  </form>
}
